import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'da' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  da: {
    'nav.home': 'Forside',
    'nav.design': 'Design selv',
    'nav.about': 'Om os',
    'nav.contact': 'Kontakt',
    'hero.title.line1': 'Design din egen',
    'hero.title.line2': 'T-shirt eller hoodie',
    'hero.subtitle': 'Hurtig levering · Ingen minimumsordre',
    'hero.cta': 'Design selv',
    'hero.price': 'Fra 299 kr',
    'home.whyChoose': 'Hvorfor vælge Nyhavn?',
    'home.whyChoose.subtitle': 'Vi leverer kvalitet, hurtighed og den bedste kundeservice i Danmark',
    'home.feature1.title': 'DTF-print teknologi',
    'home.feature1.desc': 'Professionel Direct-to-Film print for skarp kvalitet',
    'home.feature2.title': 'Holdbare farver',
    'home.feature2.desc': 'Farver der holder i mange år uden at falme',
    'home.feature3.title': '100+ vaske',
    'home.feature3.desc': 'Testet til at holde mindst 100 vaske',
    'home.feature4.title': 'Levering 2-4 hverdage',
    'home.feature4.desc': 'Hurtig produktion og forsendelse i Danmark',
    'home.howItWorks': 'Sådan fungerer det',
    'home.howItWorks.subtitle': 'Fra idé til færdigt produkt på kun 3 nemme trin',
    'home.step1.title': 'Vælg dit produkt',
    'home.step1.desc': 'T-shirts og hoodies i forskellige farver og størrelser',
    'home.step2.title': 'Design det',
    'home.step2.desc': 'Upload dit design eller brug vores designværktøj',
    'home.step3.title': 'Modtag det',
    'home.step3.desc': 'Vi printer og sender inden for 2-4 hverdage',
    'home.step1.number': 'Vælg produkt',
    'home.step1.number.desc': 'Vælg mellem T-shirt eller hoodie i forskellige farver og størrelser',
    'home.step2.number': 'Design dit motiv',
    'home.step2.number.desc': 'Upload dit eget design eller logo og se det live på produktet',
    'home.step3.number': 'Bestil og modtag',
    'home.step3.number.desc': 'Betal sikkert og modtag dit custom produkt inden for 2-4 hverdage',
    'home.whatIsPOD': 'Hvad er Print on Demand?',
    'home.whatIsPOD.p1': 'Print on Demand (POD) tilbyder en problemfri måde at skabe produkter af høj kvalitet og sælge dem direkte til kunder. Denne metode giver dig mulighed for at tilbyde personaliserede varer uden behov for at administrere lager eller forsendelseslogistik.',
    'home.whatIsPOD.p2': 'Med Nyhavn POD tager vi os af produktion og forsendelse af dine produkter på bestilling, hvilket gør det nemt at sælge custom tøj.',
    'home.deliveryTime': 'Leveringstid:',
    'home.deliveryDays': '2-4 hverdage',
    'products.title': 'Populære Produkter',
    'products.tshirt': 'T-Shirt',
    'products.hoodie': 'Hættetrøje',
    'products.mug': 'Krus',
    'products.poster': 'Plakat',
    'products.price': 'Fra',
    'products.customize': 'Tilpas',
    'features.title': 'Hvorfor Vælge Os',
    'features.quality.title': 'Premium Kvalitet',
    'features.quality.desc': 'Vi bruger kun de bedste materialer',
    'features.shipping.title': 'Hurtig Levering',
    'features.shipping.desc': 'Levering på 3-5 hverdage',
    'features.design.title': 'Tilpassede Designs',
    'features.design.desc': 'Upload dit eget design eller vælg fra vores galleri',
    'features.support.title': 'Kundeservice',
    'features.support.desc': '24/7 support til at hjælpe dig',
    'about.title': 'Om NYHAVN Print',
    'about.subtitle': 'Vi er dit lokale print-on-demand firma i hjertet af København, specialiseret i at skabe unikke T-shirts og hoodies af højeste kvalitet.',
    'about.story': 'Vores historie',
    'about.story.p1': 'Nyhavn Print on Demand blev grundlagt med en simpel vision: at gøre det nemt og overkommeligt for alle at skabe deres eget unikke tøj. Vi startede i det historiske Nyhavn-område i København og har siden specialiseret os i print-on-demand løsninger.',
    'about.story.p2': 'Med vores moderne DTF-print teknologi sikrer vi, at hvert design bliver trykt med den højeste kvalitet og holdbarhed. Vi tror på, at alle fortjener at udtrykke deres personlighed gennem deres tøj, og vi er her for at gøre det muligt.',
    'about.story.p3': 'Fra vores base på Nyhavn 44 betjener vi kunder i hele Danmark med hurtig levering og exceptionel kundeservice.',
    'about.findUs': 'Find os',
    'about.address': 'Adresse',
    'about.address.text': 'Nyhavn 44\n1051 København',
    'about.hours': 'Åbningstider',
    'about.hours.text': 'Mandag - Fredag: 9:00 - 17:00\nWeekend: Lukket',
    'about.note': 'Bemærk:',
    'about.note.text': 'Vi er primært et online firma. Kontakt os venligst på forhånd hvis du ønsker at besøge vores lokation.',
    'about.values': 'Vores værdier',
    'about.value1.title': 'Kvalitet først',
    'about.value1.desc': 'Vi bruger kun de bedste materialer og print-teknologier for at sikre holdbare produkter.',
    'about.value2.title': 'Kundetilfredshed',
    'about.value2.desc': 'Din tilfredshed er vores prioritet. Vi går den ekstra mil for at sikre en fantastisk oplevelse.',
    'about.value3.title': 'Pålidelighed',
    'about.value3.desc': 'Vi leverer til tiden, hver gang. Du kan stole på os til at opfylde dine forventninger.',
    'about.team': 'Mød teamet',
    'about.team1.title': 'Design Team',
    'about.team1.desc': 'Vores kreative team hjælper med at bringe dine ideer til live med professionel grafisk design.',
    'about.team2.title': 'Produktion',
    'about.team2.desc': 'Vores erfarne produktionsteam sikrer, at hvert produkt møder vores høje kvalitetsstandarder.',
    'about.team3.title': 'Kundeservice',
    'about.team3.desc': 'Vores venlige kundeservice team er altid klar til at hjælpe dig med spørgsmål og support.',
    'about.stat1': '1000+',
    'about.stat1.desc': 'Tilfredse kunder',
    'about.stat2': '5000+',
    'about.stat2.desc': 'Produkter leveret',
    'about.stat3': '2-4',
    'about.stat3.desc': 'Dages levering',
    'about.stat4': '4.8★',
    'about.stat4.desc': 'Gennemsnitlig rating',
    'about.cta.title': 'Klar til at starte dit projekt?',
    'about.cta.subtitle': 'Lad os hjælpe dig med at skabe det perfekte custom tøj',
    'contact.title': 'Kontakt Os',
    'contact.subtitle': 'Har du spørgsmål? Vi er her for at hjælpe!',
    'contact.name': 'Navn',
    'contact.email': 'Email',
    'contact.message': 'Besked',
    'contact.send': 'Send Besked',
    'contact.sending': 'Sender...',
    'contact.success': 'Tak for din besked! Vi vender tilbage hurtigst muligt.',
    'contact.error': 'Der opstod en fejl. Prøv venligst igen.',
    'design.title': 'Design Dit Produkt',
    'design.upload': 'Upload Dit Design',
    'design.text': 'Tilføj Tekst',
    'design.color': 'Farve',
    'design.price': 'Pris',
    'design.addToCart': 'Tilføj til Kurv',
    'design.product': 'Produkt',
    'design.size': 'Størrelse',
    'design.remove': 'Fjern Design',
    'design.textPlaceholder': 'Din tekst her...',
    'cart.title': 'Din Kurv',
    'cart.empty': 'Din kurv er tom',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Fragt',
    'cart.total': 'Total',
    'cart.checkout': 'Gå til Betaling',
    'cart.continueShopping': 'Fortsæt med at handle',
    'cart.remove': 'Fjern',
    'checkout.title': 'Checkout',
    'checkout.contactInfo': 'Kontaktinformation',
    'checkout.firstName': 'Fornavn',
    'checkout.lastName': 'Efternavn',
    'checkout.phone': 'Telefon',
    'checkout.shippingAddress': 'Leveringsadresse',
    'checkout.address': 'Adresse',
    'checkout.city': 'By',
    'checkout.postalCode': 'Postnummer',
    'checkout.country': 'Land',
    'checkout.orderSummary': 'Ordre Oversigt',
    'checkout.placeOrder': 'Afgiv Ordre',
    'checkout.processing': 'Behandler...',
    'checkout.success': 'Tak for din ordre! Vi sender en bekræftelse til din email.',
    'checkout.error': 'Der opstod en fejl. Prøv venligst igen.',
    'footer.company': 'Firma',
    'footer.support': 'Support',
    'footer.legal': 'Juridisk',
    'footer.privacy': 'Privatlivspolitik',
    'footer.terms': 'Vilkår & Betingelser',
    'footer.rights': 'Alle rettigheder forbeholdes.',
    'size.small': 'Lille',
    'size.medium': 'Medium',
    'size.large': 'Stor',
    'size.xlarge': 'X-Stor',
  },
  en: {
    'nav.home': 'Home',
    'nav.design': 'Design Yourself',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'hero.title.line1': 'Design your own',
    'hero.title.line2': 'T-shirt or hoodie',
    'hero.subtitle': 'Fast delivery · No minimum order',
    'hero.cta': 'Design now',
    'hero.price': 'From 299 kr',
    'home.whyChoose': 'Why choose Nyhavn?',
    'home.whyChoose.subtitle': 'We deliver quality, speed and the best customer service in Denmark',
    'home.feature1.title': 'DTF-print technology',
    'home.feature1.desc': 'Professional Direct-to-Film print for sharp quality',
    'home.feature2.title': 'Durable colors',
    'home.feature2.desc': 'Colors that last for many years without fading',
    'home.feature3.title': '100+ washes',
    'home.feature3.desc': 'Tested to last at least 100 washes',
    'home.feature4.title': 'Delivery 2-4 business days',
    'home.feature4.desc': 'Fast production and shipping in Denmark',
    'home.howItWorks': 'How it works',
    'home.howItWorks.subtitle': 'From idea to finished product in just 3 easy steps',
    'home.step1.title': 'Choose your product',
    'home.step1.desc': 'T-shirts and hoodies in various colors and sizes',
    'home.step2.title': 'Design it',
    'home.step2.desc': 'Upload your design or use our design tool',
    'home.step3.title': 'Receive it',
    'home.step3.desc': 'We print and ship within 2-4 business days',
    'home.step1.number': 'Choose product',
    'home.step1.number.desc': 'Choose between T-shirt or hoodie in different colors and sizes',
    'home.step2.number': 'Design your motif',
    'home.step2.number.desc': 'Upload your own design or logo and see it live on the product',
    'home.step3.number': 'Order and receive',
    'home.step3.number.desc': 'Pay securely and receive your custom product within 2-4 business days',
    'home.whatIsPOD': 'What is Print on Demand?',
    'home.whatIsPOD.p1': 'Print on Demand (POD) offers a hassle-free way to create high-quality products and sell them directly to customers. This method allows you to offer personalized items without the need to manage inventory or shipping logistics.',
    'home.whatIsPOD.p2': 'With Nyhavn POD, we handle production and shipping of your products on demand, making it easy to sell custom clothing.',
    'home.deliveryTime': 'Delivery time:',
    'home.deliveryDays': '2-4 business days',
    'products.title': 'Popular Products',
    'products.tshirt': 'T-Shirt',
    'products.hoodie': 'Hoodie',
    'products.mug': 'Mug',
    'products.poster': 'Poster',
    'products.price': 'From',
    'products.customize': 'Customize',
    'features.title': 'Why Choose Us',
    'features.quality.title': 'Premium Quality',
    'features.quality.desc': 'We only use the best materials',
    'features.shipping.title': 'Fast Delivery',
    'features.shipping.desc': 'Delivery in 3-5 business days',
    'features.design.title': 'Custom Designs',
    'features.design.desc': 'Upload your own design or choose from our gallery',
    'features.support.title': 'Customer Service',
    'features.support.desc': '24/7 support to help you',
    'about.title': 'About NYHAVN Print',
    'about.subtitle': 'We are your local print-on-demand company in the heart of Copenhagen, specialized in creating unique T-shirts and hoodies of the highest quality.',
    'about.story': 'Our story',
    'about.story.p1': 'Nyhavn Print on Demand was founded with a simple vision: to make it easy and affordable for everyone to create their own unique clothing. We started in the historic Nyhavn area of Copenhagen and have since specialized in print-on-demand solutions.',
    'about.story.p2': 'With our modern DTF-print technology, we ensure that every design is printed with the highest quality and durability. We believe that everyone deserves to express their personality through their clothing, and we are here to make that possible.',
    'about.story.p3': 'From our base at Nyhavn 44, we serve customers throughout Denmark with fast delivery and exceptional customer service.',
    'about.findUs': 'Find us',
    'about.address': 'Address',
    'about.address.text': 'Nyhavn 44\n1051 Copenhagen',
    'about.hours': 'Opening hours',
    'about.hours.text': 'Monday - Friday: 9:00 - 17:00\nWeekend: Closed',
    'about.note': 'Note:',
    'about.note.text': 'We are primarily an online company. Please contact us in advance if you wish to visit our location.',
    'about.values': 'Our values',
    'about.value1.title': 'Quality first',
    'about.value1.desc': 'We only use the best materials and print technologies to ensure durable products.',
    'about.value2.title': 'Customer satisfaction',
    'about.value2.desc': 'Your satisfaction is our priority. We go the extra mile to ensure a fantastic experience.',
    'about.value3.title': 'Reliability',
    'about.value3.desc': 'We deliver on time, every time. You can count on us to meet your expectations.',
    'about.team': 'Meet the team',
    'about.team1.title': 'Design Team',
    'about.team1.desc': 'Our creative team helps bring your ideas to life with professional graphic design.',
    'about.team2.title': 'Production',
    'about.team2.desc': 'Our experienced production team ensures that every product meets our high quality standards.',
    'about.team3.title': 'Customer Service',
    'about.team3.desc': 'Our friendly customer service team is always ready to help you with questions and support.',
    'about.stat1': '1000+',
    'about.stat1.desc': 'Satisfied customers',
    'about.stat2': '5000+',
    'about.stat2.desc': 'Products delivered',
    'about.stat3': '2-4',
    'about.stat3.desc': 'Days delivery',
    'about.stat4': '4.8★',
    'about.stat4.desc': 'Average rating',
    'about.cta.title': 'Ready to start your project?',
    'about.cta.subtitle': 'Let us help you create the perfect custom clothing',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions? We\'re here to help!',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Thank you for your message! We\'ll get back to you as soon as possible.',
    'contact.error': 'An error occurred. Please try again.',
    'design.title': 'Design Your Product',
    'design.upload': 'Upload Your Design',
    'design.text': 'Add Text',
    'design.color': 'Color',
    'design.price': 'Price',
    'design.addToCart': 'Add to Cart',
    'design.product': 'Product',
    'design.size': 'Size',
    'design.remove': 'Remove Design',
    'design.textPlaceholder': 'Your text here...',
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'checkout.title': 'Checkout',
    'checkout.contactInfo': 'Contact Information',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.phone': 'Phone',
    'checkout.shippingAddress': 'Shipping Address',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.postalCode': 'Postal Code',
    'checkout.country': 'Country',
    'checkout.orderSummary': 'Order Summary',
    'checkout.placeOrder': 'Place Order',
    'checkout.processing': 'Processing...',
    'checkout.success': 'Thank you for your order! We\'ll send a confirmation to your email.',
    'checkout.error': 'An error occurred. Please try again.',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.rights': 'All rights reserved.',
    'size.small': 'Small',
    'size.medium': 'Medium',
    'size.large': 'Large',
    'size.xlarge': 'X-Large',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'da';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
